---
abstract: 'CPAN Testers Release Summary'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  LWP::Online: 1.07
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: ORDB::CPANRelease
name: ORDB-CPANRelease
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  ORLite::Mirror: 1.12
  Params::Util: 0.38
  perl: 5.8.5
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/ORDB-CPANRelease
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/ORDB-CPANRelease
version: 0.01
